### PR TITLE
manage grub password

### LINKED ISSUE #3: Manage grub password
## Proposed feature

Add the ability to set a password for modifying grub

## Rationale

To protect unwanted changes on the boot command

### PR DESCRIPTION
**Pull request by Tuxem**
fix #3

### CODE REVIEW

**Comment by robertdebock** [comment]
Thanks, looks great. Waiting for CI.

**Comment by robertdebock** [comment]
Couple of issue, listing mostly:

```
literal-compare: Don't compare to literal True/False
``` 

You can rewrite these:

```yaml
when: grub_efi.stat.exists == True
```

to:

```yaml
when: grub_efi.stat.exists
```

(Not having `== True` does exactly the same. I know; it's weird.)

**Comment by sumasagrp** [comment]
could this be merged ? this is a great feature

**Comment by robertdebock** [comment]
Great PR, thanks!

**Pull request merged**
